"""Configure trace layouts for app."""

layout_2d = dict(
    height=550,
    margin={"t": 30, "l": 60, "b": 0, "r": 5},
    yaxis_range=[0, 1],
    xaxis_range=[0, 1],
    showlegend=False,
    coloraxis_showscale=False,
    clickmode="event",
    plot_bgcolor="rgb(255,255,255)",
    xaxis=dict(
        showgrid=True,
        gridcolor="lightgrey",
        title="Tag X",
        showline=True,
        linecolor="black",
        linewidth=2,
        mirror=True,
    ),
    yaxis=dict(
        showgrid=True,
        gridcolor="lightgrey",
        title="Tag Y",
        showline=True,
        linecolor="black",
        linewidth=2,
        mirror=True,
    ),
    title=dict(
        text="Density Function",
        x=0.5,
        y=0.94,
        yanchor="top",
        xanchor="center",
    ),
    title_font=dict(family="Verdana", size=16, color="black"),
)

layout_x = dict(
    height=350,
    margin={"t": 30, "l": 60, "b": 15, "r": 5},
    xaxis_range=[0, 1],
    showlegend=False,
    plot_bgcolor="rgb(255,255,255)",
    xaxis=dict(
        showgrid=True,
        showticklabels=False,
        gridcolor="lightgrey",
        showline=True,
        linecolor="black",
        linewidth=2,
        mirror=False,
    ),
    yaxis=dict(
        showgrid=True,
        gridcolor="lightgrey",
        title="P(x)",
        showline=True,
        linecolor="black",
        linewidth=2,
        zeroline=True,
        zerolinewidth=2,
        zerolinecolor="black",
        rangemode="tozero",
        mirror=False,
    ),
)

# Configure figure layout
layout_y = dict(
    height=530,
    margin={"t": 20, "l": 10, "b": 0, "r": 5},
    yaxis_range=[0, 1],
    showlegend=False,
    plot_bgcolor="rgb(255,255,255)",
    xaxis=dict(
        showgrid=True,
        gridcolor="lightgrey",
        title="P(x)",
        zeroline=True,
        zerolinewidth=2,
        zerolinecolor="black",
        showline=True,
        linecolor="black",
        linewidth=2,
        mirror=False,
        rangemode="tozero",
    ),
    yaxis=dict(
        showgrid=True,
        showticklabels=False,
        gridcolor="lightgrey",
        showline=True,
        linecolor="black",
        rangemode="tozero",
        linewidth=2,
        mirror=False,
    ),
)

layout_scoring = dict(
    height=900,
    margin={"t": 30, "l": 40, "b": 0, "r": 5},
    showlegend=False,
    plot_bgcolor="rgb(255,255,255)",
    yaxis_range=[0, 1],
    xaxis_range=[0, 1],
    xaxis=dict(
        title="P(x,y)",
        gridcolor="lightgrey",
        showgrid=True,
        showline=True,
        linecolor="black",
        linewidth=2,
        mirror=True,
    ),
    yaxis=dict(
        side="right",
        title="Pr[L\u2093 \u2264 P(x,y)]",
        gridcolor="lightgrey",
        showgrid=True,
        showline=True,
        linecolor="black",
        linewidth=2,
        zeroline=True,
        zerolinewidth=2,
        zerolinecolor="black",
        mirror=True,
    ),
    title=dict(
        text="Scoring Function",
        x=0.5,
        y=0.96,
        yanchor="top",
        xanchor="center",
    ),
    title_font=dict(family="Verdana", size=16, color="black"),
)
